import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        black: "#000",
        brand: "#a62626",
        white: "#fff",
        gray: "#030303",
        message: "#f0faff",
        error: "#ff0000",
        warning: "#e65100",
        tertiary: "#2670c1",
        "success-primary": "#2e7d32",
        input: "#f0f0f1",
        "success-secondary": "#7cb342",
        "success-divider": "rgba(46, 125, 50, 0.12)",
        "blue-800": "#0c69d4",
        "blue-outline": "#39f",
        "warning-primary": "#e65100",
        "warning-hint": "rgba(230, 81, 0, 0.12)",
        "warning-secondary": "#fbc02d",
        "warning-secondary-hint": "rgba(251, 192, 45, 0.12)",
        "message-primary": "#f0faff",
        "message-secondary": "#dbf3ff",
        "message-opposite-primary": "#f5f5f5",
        "message-opposite-secondary": "#e6e6e6",
        "message-hint": "rgba(240, 250, 255, 0.32)",
        "error-primary": "#ff0000",
        "error-hint": "rgba(255, 0, 0, 0.08)",
        "white-primary": "#fff",
        "white-nav": "hsla(0, 0%, 100%, 0.98)",
        "white-secondary": "hsla(0, 0%, 100%, 0.7)",
        "white-hint": "hsla(0, 0%, 100%, 0.5)",
        "white-divider": "hsla(0, 0%, 100%, 0.12)",
        transparent: "hsla(0, 0%, 100%, 0.01)",
        "black-primary": "rgba(0, 0, 0, 0.87)",
        "black-secondary": "rgba(0, 0, 0, 0.56)",
        "black-dark-100": "rgba(0, 0, 0, 0.48)",
        "black-hint": "rgba(0, 0, 0, 0.32)",
        "black-medium-200": "rgba(0, 0, 0, 0.24)",
        "black-medium-100": "rgba(0, 0, 0, 0.16)",
        "black-divider": "rgba(0, 0, 0, 0.12)",
        "black-light-200": "rgba(0, 0, 0, 0.08)",
        "black-light-100": "rgba(0, 0, 0, 0.04)",
        "black-press": "rgba(0, 0, 0, 0.6)",
        "black-tooltip": "#292929",
        "black-hover": "rgba(31, 31, 31, 0.56)",
        "static-white": "#fff",
        "surface-primary": "#fff",
        "surface-secondary": "#f4f4f5",
        "surface-tertiary": "#e4e4e7",
        "surface-inverted-primary": "#2c2c30",
        "surface-inverted-secondary": "#52525b",
        "surface-inverted-tertiary": "#a1a1aa",
        "surface-informative-primary": "#3062d4",
        "surface-informative-secondary": "#99b7f7",
        "surface-informative-tertiary": "#d7e4ff",
        "surface-informative-quaternary": "#e5eeff",
        "surface-positive-primary": "#1d7c4d",
        "surface-positive-secondary": "#75cc9e",
        "surface-positive-tertiary": "#c6f1da",
        "surface-positive-quaternary": "#d8f8e7",
        "surface-warning-primary": "#e68f38",
        "surface-warning-secondary": "#feb872",
        "surface-warning-tertiary": "#fcdec0",
        "surface-warning-quaternary": "#ffe8d1",
        "surface-negative-primary": "#c53434",
        "surface-negative-secondary": "#f49090",
        "surface-negative-tertiary": "#fcd9d9",
        "surface-negative-quaternary": "#fee6e6",
        "surface-brand-primary": "#d10f0f",
        "surface-brand-secondary": "#e88787",
        "surface-brand-tertiary": "#fcc9c9",
        "surface-brand-quaternary": "#fae7e7",
        "surface-accent-primary": "#ffb200",
        "surface-accent-secondary": "#ffc94d",
        "surface-accent-tertiary": "#ffe8b3",
        "surface-accent-quaternary": "#fff5e1",
        "surface-dimmer-primary": "rgba(0, 0, 0, 0.32)",
        "surface-dimmer-secondary": "rgba(0, 0, 0, 0.64)",
        "surface-dimmer-inverted-primary": "hsla(0, 0%, 100%, 0.32)",
        "surface-dimmer-inverted-secondary": "hsla(0, 0%, 100%, 0.64)",
        "surface-dimmer-brand-primary": "rgba(209, 15, 15, 0.16)",
        "surface-dimmer-brand-secondary": "rgba(209, 15, 15, 0.32)",
        "content-primary": "#2c2c30",
        "content-secondary": "#71717a",
        "content-tertiary": "#a1a1aa",
        "content-quaternary": "#dbdbe4",
        "content-inverted-primary": "#fff",
        "content-inverted-secondary": "#f4f4f5",
        "content-inverted-tertiary": "#dbdbe4",
        "content-inverted-quaternary": "#a1a1aa",
        "content-on-brand": "#fff",
        "content-informative-primary": "#3062d4",
        "content-informative-secondary": "#6792f4",
        "content-positive-primary": "#1d7c4d",
        "content-positive-secondary": "#4aa578",
        "content-warning-primary": "#d86f06",
        "content-warning-secondary": "#f6a351",
        "content-negative-primary": "#c53434",
        "content-negative-secondary": "#f26464",
        "content-brand-primary": "#d10f0f",
        "content-brand-secondary": "#df5757",
        "content-brand-tertiary": "#fcc9c9",
        "content-brand-inverted": "#e88787",
        "border-primary": "#71717a",
        "border-secondary": "#a1a1aa",
        "border-tertiary": "#dbdbe4",
        "border-inverted-primary": "#fff",
        "border-informative-primary": "#3062d4",
        "border-informative-secondary": "#99b7f7",
        "border-informative-tertiary": "#cdddff",
        "border-positive-primary": "#1d7c4d",
        "border-positive-secondary": "#75cc9e",
      },
    },
  },
  plugins: [],
};

export default config;
